services:
  # Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1m
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
        echo 'Starting Ollama server...' &&
        ollama serve &

        echo 'Waiting for Ollama to become healthy...'
        until curl -sf http://localhost:11434/api/tags; do
          sleep 2
        done

        # echo 'Pulling mistral model...'
        # ollama pull mistral

        echo 'Ollama is ready.'
        tail -f /dev/null
      "

  # Research Assistant API
  research-assistant:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env


volumes:
  ollama_data:

networks:
  default:
    name: rag-network
