version: '3.8'

services:
  # Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      ollama serve &&
      sleep 3 &&
      ollama pull mistral &&
      tail -f /dev/null
      "

  # Research Assistant API
  research-assistant:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data:

networks:
  default:
    name: rag-network



